### ISSUE TITLE
Need DeepPlpModule version up

### ISSUE THREAD

**Issue by ChungsooKim** [ohdsi-studies/DeepLearningComparison#5]
The current version of DeepPatientLevelPredictionModule in the study json is v0.0.1, however, it throws an error related to '.Rprofile'.
![image](https://user-images.githubusercontent.com/42205861/226313130-26b850ed-6000-41f9-82ff-2d8026fff6d9.png)

In the previous [PR](https://github.com/OHDSI/DeepPatientLevelPredictionModule/pull/2), this error was resolved already, therefore needs a version up.

**Comment by egillax** [comment]
Closing, this has been fixed.
